[package]
name = "magnet-uri"
version = "0.1.0"
authors = ["Jakub Jaroszewski <jakub.jaroszewski@gmail.com>"]
repository = "https://github.com/pierd/magnet-uri"
keywords = ["magnet", "bittorrent"]
readme = "README.md"
license = "MIT"

[dependencies]
serde_urlencoded = "0.5.3"
